### ISSUE TITLE
Question: existence reason of param `firebase_cli_path`

### ISSUE THREAD

**Issue by snowtema** [fastlane-community/fastlane-plugin-firebase_app_distribution#13]
What is profit to manual setting up this param? At least, you could provide some instructions to determine this path, because sometimes it's really hard to find it.

**Comment by rebehe** [comment]
Hi Tema! This is Rebecca, an engineer on the App Distribution team. So it depends on if you're using the standalone binary or the npm firebase-tools https://firebase.google.com/docs/cli. By default, fastlane will try to find the Firebase CLI using the `firebase` alias. If you're using the npm firebase-tools, then the `firebase_cli_path` is not required. If you're using the standalone binary, this param is required if you don't have it set to the `firebase` alias.

Good feedback that the instructions could be more clear. We're in the process of updating them :)
