### ISSUE TITLE
Firebase app distribution failing with unknown keyword: default_value_dynamic error

### ISSUE THREAD

**Issue by pollux-** [fastlane-community/fastlane-plugin-firebase_app_distribution#17]
$ fastlane android distribute
+------------------------+---------+------------------------+
|                       Used plugins                        |
+------------------------+---------+------------------------+
| Plugin                 | Version | Action                 |
+------------------------+---------+------------------------+
| fastlane-plugin-fireb  | 0.1.4   | firebase_app_distribu  |
| ase_app_distribution   |         | tion                   |
+------------------------+---------+------------------------+

[18:03:29]: Your Fastfile has had smart quotes sanitised. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.
[18:03:30]: -------------------------------------------------
[18:03:30]: --- Step: Verifying required fastlane version ---
[18:03:30]: -------------------------------------------------
[18:03:30]: Your fastlane version 2.28.3 matches the minimum requirement of 2.28.3  ✅
[18:03:30]: ------------------------------
[18:03:30]: --- Step: default_platform ---
[18:03:30]: ------------------------------
[18:03:30]: Driving the lane 'android distribute' 🚀
[18:03:30]: --------------------
[18:03:30]: --- Step: gradle ---
[18:03:30]: --------------------
[18:03:30]: $ /Users/sreekumarav/development/android-architecture-components/AndroidKoin/gradlew assembleDebug -p .
[18:03:30]: ▸ > Task :app:preBuild UP-TO-DATE
[18:03:30]: ▸ > Task :app:preDebugBuild UP-TO-DATE
[18:03:30]: ▸ > Task :app:checkDebugManifest UP-TO-DATE
[18:03:30]: ▸ > Task :app:generateDebugBuildConfig UP-TO-DATE
[18:03:30]: ▸ > Task :app:compileDebugAidl NO-SOURCE
[18:03:30]: ▸ > Task :app:compileDebugRenderscript NO-SOURCE
[18:03:30]: ▸ > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[18:03:30]: ▸ > Task :app:generateDebugResValues UP-TO-DATE
[18:03:30]: ▸ > Task :app:generateDebugResources UP-TO-DATE
[18:03:30]: ▸ > Task :app:processDebugGoogleServices UP-TO-DATE
[18:03:30]: ▸ > Task :app:mergeDebugResources UP-TO-DATE
[18:03:30]: ▸ > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[18:03:30]: ▸ > Task :app:processDebugManifest UP-TO-DATE
[18:03:30]: ▸ > Task :app:processDebugResources UP-TO-DATE
[18:03:30]: ▸ > Task :app:compileDebugKotlin UP-TO-DATE
[18:03:30]: ▸ > Task :app:javaPreCompileDebug UP-TO-DATE
[18:03:30]: ▸ > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[18:03:30]: ▸ > Task :app:compileDebugSources UP-TO-DATE
[18:03:30]: ▸ > Task :app:mergeDebugShaders UP-TO-DATE
[18:03:30]: ▸ > Task :app:compileDebugShaders UP-TO-DATE
[18:03:30]: ▸ > Task :app:generateDebugAssets UP-TO-DATE
[18:03:30]: ▸ > Task :app:mergeDebugAssets UP-TO-DATE
[18:03:30]: ▸ > Task :app:processDebugJavaRes NO-SOURCE
[18:03:30]: ▸ > Task :app:mergeDebugJavaResource UP-TO-DATE
[18:03:30]: ▸ > Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
[18:03:30]: ▸ > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[18:03:30]: ▸ > Task :app:mergeLibDexDebug UP-TO-DATE
[18:03:30]: ▸ > Task :app:mergeExtDexDebug UP-TO-DATE
[18:03:30]: ▸ > Task :app:mergeProjectDexDebug UP-TO-DATE
[18:03:30]: ▸ > Task :app:validateSigningDebug UP-TO-DATE
[18:03:30]: ▸ > Task :app:signingConfigWriterDebug UP-TO-DATE
[18:03:30]: ▸ > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[18:03:30]: ▸ > Task :app:mergeDebugNativeLibs UP-TO-DATE
[18:03:30]: ▸ > Task :app:stripDebugDebugSymbols UP-TO-DATE
[18:03:30]: ▸ > Task :app:packageDebug UP-TO-DATE
[18:03:30]: ▸ > Task :app:assembleDebug UP-TO-DATE
[18:03:30]: ▸ BUILD SUCCESSFUL in 0s
[18:03:30]: ▸ 27 actionable tasks: 27 up-to-date
[18:03:31]: Couldn't find any new signed apk files...
[18:03:31]: ---------------------------------------
[18:03:31]: --- Step: firebase_app_distribution ---
[18:03:31]: ---------------------------------------
[18:03:31]: You passed invalid parameters to 'firebase_app_distribution'.
[18:03:31]: Check out the error below and available options by running `fastlane action firebase_app_distribution`
+-----------------------------+--------------------+
|                   Lane Context                   |
+-----------------------------+--------------------+
| DEFAULT_PLATFORM            | android            |
| PLATFORM_NAME               | android            |
| LANE_NAME                   | android distribute |
| GRADLE_BUILD_TYPE           | Debug              |
| GRADLE_ALL_APK_OUTPUT_PATHS | []                 |
+-----------------------------+--------------------+
[18:03:31]: unknown keyword: default_value_dynamic

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | Verifying required     | 0           |
|      | fastlane version       |             |
| 2    | default_platform       | 0           |
| 3    | gradle                 | 1           |
| 💥   | firebase_app_distribu  | 0           |
|      | tion                   |             |
+------+------------------------+-------------+

[18:03:31]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane_core/lib/fastlane_core/configuration/config_item.rb:58:in `initialize': [!] unknown keyword: default_value_dynamic (ArgumentError)
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-plugin-firebase_app_distribution-0.1.4/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb:65:in `new'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-plugin-firebase_app_distribution-0.1.4/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb:65:in `available_options'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/configuration_helper.rb:4:in `parse'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:236:in `block (2 levels) in execute_action'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:226:in `chdir'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:50:in `block (2 levels) in parsing_binding'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:40:in `run!'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/sreekumarav/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.3/bin/fastlane:20:in `<top (required)>'
	from /Users/sreekumarav/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/sreekumarav/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.6 (18G95)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.3                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.3"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end

  desc "Deploying Debug build to firebase"
      lane :distribute do
        gradle(
            task: 'assemble',
            build_type: ‘Debug’
          )

          firebase_app_distribution(
              app: "1:717023762309:android:1a7c9bca3ad336709656ec",
              release_notes: "Lots of amazing new features to test out!",
              firebase_cli_path: "/usr/local/bin/firebase"
          )

      end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "com.koin.sample" # e.g. com.krausefx.app
```
</details>

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.28.3  | 💥 Check failed |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status  |
| ----------------------------------------- | ------- | -------------- |
| fastlane-plugin-firebase_app_distribution | 0.1.4   | 💥 Check failed |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| slack-notifier                            | 1.5.1        |
| atomos                                    | 0.1.3        |
| CFPropertyList                            | 2.3.5        |
| claide                                    | 1.0.3        |
| colored2                                  | 3.1.2        |
| nanaimo                                   | 0.2.6        |
| xcodeproj                                 | 1.12.0       |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| terminal-notifier                         | 1.7.1        |
| unicode-display_width                     | 1.1.3        |
| terminal-table                            | 1.7.3        |
| plist                                     | 3.2.0        |
| public_suffix                             | 2.0.5        |
| addressable                               | 2.5.1        |
| multipart-post                            | 2.0.0        |
| word_wrap                                 | 1.0.0        |
| tty-screen                                | 0.5.0        |
| babosa                                    | 1.0.2        |
| colored                                   | 1.2          |
| highline                                  | 1.7.8        |
| commander-fastlane                        | 4.4.6        |
| excon                                     | 0.55.0       |
| faraday                                   | 0.12.1       |
| unf_ext                                   | 0.0.7.4      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20170404 |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.6        |
| fastimage                                 | 2.1.0        |
| gh_inspector                              | 1.1.3        |
| uber                                      | 0.0.15       |
| representable                             | 2.3.0        |
| retriable                                 | 2.1.0        |
| mime-types-data                           | 3.2016.0521  |
| mime-types                                | 3.1          |
| hurley                                    | 0.2          |
| little-plugger                            | 1.1.4        |
| multi_json                                | 1.12.1       |
| logging                                   | 2.2.2        |
| jwt                                       | 1.5.6        |
| memoist                                   | 0.16.0       |
| os                                        | 0.9.6        |
| signet                                    | 0.7.3        |
| googleauth                                | 0.5.1        |
| httpclient                                | 2.8.3        |
| google-api-client                         | 0.9.28       |
| json                                      | 1.8.1        |
| mini_magick                               | 4.5.1        |
| multi_xml                                 | 0.6.0        |
| rubyzip                                   | 1.3.0        |
| security                                  | 0.1.3        |
| xcpretty-travis-formatter                 | 0.0.4        |
| dotenv                                    | 2.2.0        |
| bundler                                   | 1.14.6       |
| faraday_middleware                        | 0.11.0.1     |
| fastlane-plugin-firebase_app_distribution | 0.1.4        |
</details>

*generated on:* **2019-10-13**
</details>

Can someone help me with this?

**Comment by froesmatheus** [comment]
Same issue here

**Comment by tonybaroneee** [comment]
Hey @pollux- and @froesmatheus, could you try upgrading your version of Ruby to 2.5?

**Comment by tonybaroneee** [comment]
Also, this is an issue around creating a FastlaneCore config item, and not specific to this plugin. Feel free to create a new issue against the main fastlane repo (https://github.com/fastlane/fastlane/issues/new) if the upgrading ruby does not address this. Thanks!

**Comment by froesmatheus** [comment]
I upgraded my Ruby version but still nothing

**Comment by fhschan-bcit** [comment]
Not sure if my solution helps - but I had the same issue when I had fastlane installed through homebrew. It worked fine when I did this on mac OSX mojave.
1. Install ruby 
2. Install ruby versioning manager (rvm)
3. Install and use the latest ruby version 2.6.4 through rvm
4. Install fastlane through ruby (not brew this time)
5. Install firebase_app_distribution through fastlane
6. Update fastlane 
7. Run your fastlane firebase lane

This issue didn't pop up afterwards.

**Comment by froesmatheus** [comment]
> Not sure if my solution helps - but I had the same issue when I had fastlane installed through homebrew. It worked fine when I did this on mac OSX mojave.
> 
> 1. Install ruby
> 2. Install ruby versioning manager (rvm)
> 3. Install and use the latest ruby version 2.6.4 through rvm
> 4. Install fastlane through ruby (not brew this time)
> 5. Install firebase_app_distribution through fastlane
> 6. Update fastlane
> 7. Run your fastlane firebase lane
> 
> This issue didn't pop up afterwards.

Yeah, after installing RVM it worked!
