### ISSUE TITLE
Does not support `appdistribution:distribute` command

### ISSUE THREAD

**Issue by djrausch** [fastlane-community/fastlane-plugin-firebase_app_distribution#2]
Getting the following error:
[!] firebase_cli_path: `/home/circleci/repo/firebase` does not support the `appdistribution:distribute` command. Please download (https://appdistro.page.link/firebase-cli-download) or specify the path to the correct version of firebase

The version downloaded does have the command.

Any ideas?

**Comment by djrausch** [comment]
Switched to not defining and letting the `which fastlane` command handle. Works now!

**Comment by Ej-leone** [comment]
could you explain this am facing this issue
