### ISSUE TITLE
[Feature request] Add a apk file name to the plugin configuration

### ISSUE THREAD

**Issue by KatieBarnett** [fastlane-community/fastlane-plugin-firebase_app_distribution#20]
The firebase_app_distribution fastlane plugin is picking up the most recent apk built - not the one the coordinated with the appId that has been set. 

So when I had the uploads happening after all flavours had been built only the last apk was uploaded. 

For example:
```
    buildApp(flavor: configAppDevelopFlavor, build_type: 'Release')
    buildApp(flavor: configAppProductionFlavor, build_type: 'Release')

    firebase_app_distribution(
      app: 'xxxx',
      groups: 'testers',
      firebase_cli_path: '/usr/local/bin/firebase',
      firebase_cli_token: 'zzzz',
      debug: true)

    firebase_app_distribution(
      app: 'yyyy',
      groups: 'testers',
      firebase_cli_path: '/usr/local/bin/firebase',
      firebase_cli_token: 'zzzz',
      debug: true)
```

Results in 2 x 'App production' apps uploaded, one to each of the Firebase projects associated with those ids. 

When I changed it to:
```
    buildApp(flavor: configAppDevelopFlavor, build_type: 'Release')
    firebase_app_distribution(
      app: 'xxxx',
      groups: 'testers',
      firebase_cli_path: '/usr/local/bin/firebase',
      firebase_cli_token: 'zzzz',
      debug: true)

    buildApp(flavor: configAppProductionFlavor, build_type: 'Release')
    firebase_app_distribution(
      app: 'yyyy',
      groups: 'testers',
      firebase_cli_path: '/usr/local/bin/firebase',
      firebase_cli_token: 'zzzz',
      debug: true)
```

Each individual app was uploaded to the correct project on firebase. 

It would be useful to have a apk filename input to the firebase_app_distribution fastlane plugin to make this clearer and allow customisation of build steps.

**Comment by rebehe** [comment]
Hi Katie, Rebecca here, an engineer on App Distribution! There actually is a flag, `apk_path`, where you can specify the path to your APK file.
