### ISSUE TITLE
 HTTP Error: 403 - caller does not have permission

### ISSUE THREAD

**Issue by claudioviola** [fastlane-community/fastlane-plugin-firebase_app_distribution#22]
Hello,
I've been facing this error
`Error: failed to fetch app information. HTTP Error: 403, The caller does not have permission`

First I run this 
`
export GOOGLE_APPLICATION_CREDENTIALS=/Users/my/..../android/secure/firebase-service-account-key.json
`

After I run this command from shell
`
fastlane run firebase_app_distribution app:y_app_id
apk_path:./app/build/outputs/apk/release/app-release.apk
`

I follow this guide to create json key
https://firebase.google.com/docs/app-distribution/authenticate-service-account.md?platform=android

How can I solve it?
Where is my mistake?

Thank you
Claudio

**Comment by lll8033** [comment]
Error “[403] The caller does not have permission.” is caused by a permission issue. ​​​​​​​

Can you try to follow[this](https://cloud.google.com/docs/authentication/production#obtaining_and_providing_service_account_credentials_manually) on how to create service account and where to download the json, to see if it works?

You are also welcome to reach out to [firebase support](https://firebase.google.com/support/troubleshooter/contact) with more info. :)

**Comment by claudioviola** [comment]
@lll8033 
Many thanks for the support. I solved.
It was my mistake about the service account role.

I'm gonna to close the issue.

Now I got 2 errors.
1 with `Error: Command requires authentication, please run firebase login`
that's why firebase_app_distribution doesn't find the file in GOOGLE_APPLICATION_CREDENTIALS

1 with 
`firebase_app_distribution: Couldn't find apk_file at path '../app/build/outputs/apk/release/app-release.apk'`
that's why firebase_app_distribution doesn't find apk file

If I use absolute paths for both it works nice

 `firebase_app_distribution` fails with relative paths for both json file and apk

My lane include this script

```
desc "Deploy to Crashlytics"
	lane :deploy_to_crashlytics do
		sh ("echo $PWD");
		sh ("echo $GOOGLE_APPLICATION_CREDENTIALS");
		firebase_app_distribution(
			app: ENV["FIREBASE_APP_ID"],
			apk_path: "../app/build/outputs/apk/release/app-release.apk",
			groups: "internal-android, internal-ios"
		)
	end
```

My current folder, when lane is running, (`echo $PWD`) is
Users/claudio/Desktop/LAB/MyProject/MyApp/android/fastlane

My files are in
/Users/claudio/Desktop/LAB/MyProject/MyApp/android/app/build/outputs/apk/release/app-release.apk
/Users/claudio/Desktop/LAB/MyProject/MyApp/android/secure/service-account-key.json

Any suggestions?

Thanks again

**Comment by asteiman** [comment]
@claudioviola could you tell me how the roles should be configured? I am facing the same error.

**Comment by rygalang** [comment]
Hi guys, same issue here. Need your help. Thanks in advance,.

**Comment by claudioviola** [comment]
@asteiman passed some month I don't remember very well but I created the service account from https://console.cloud.google.com/

I reached this page from Firebase website > Settings > Service Account > Manage Service Account

Furthermore I found out it was required using the absolute full path for the service account file in the
`export GOOGLE_APPLICATION_CREDENTIALS=`
and not the relative path

Anyway if your firebase upload command is correct you should be sure to create properly the firebase service account

**Comment by leblancmeneses** [comment]
Go to IAM https://console.cloud.google.com/iam-admin/iam
Then add Firebase App Distribution Admin  to the service account you are using.

Docs: https://firebase.google.com/docs/app-distribution/authenticate-service-account?platform=ios
