### ISSUE TITLE
how to distribute aab file

### ISSUE THREAD

**Issue by shiratsu** [fastlane-community/fastlane-plugin-firebase_app_distribution#26]
i would like to distribute app bundle through this plugin but i can't.
i explored this document, it does not have such a function.
does it have this way?
or do you have a plan it will be implemented?

**Comment by shiratsu** [comment]
i got to know firebase_app_distribution doesnt have this way
i will close

**Comment by NikhileshMindTickle** [comment]
Please check with this code.
Source : https://firebase.google.com/docs/app-distribution/android/distribute-fastlane?apptype=aab
```
platform :android do
    desc "My awesome app"
    lane :distribute do
        build_android_app(task: "bundle", ...)
        # build_android_app is a built-in fastlane action.

        firebase_app_distribution(
            app: "1:123456789:android:abcd1234",
            testers: "tester1@company.com, tester2@company.com",
            release_notes: "Lots of amazing new features to test out!",
            android_artifact_type="AAB"
        )

    end
end
```

**Comment by tagboola** [comment]
@NikhileshMindTickle yes this looks good. For reference, we [launched AAB support last week](https://firebase.google.com/support/releases#appdistro-aab-support). Make sure you follow the steps in the[ Before you begin](https://firebase.google.com/docs/app-distribution/android/distribute-fastlane?apptype=aab#before_you_begin) section as they are required to upload AAB's.

**Comment by nidovic** [comment]
platform :android do
    desc "My awesome app"
    lane :distribute do
        build_android_app(task: "bundle", ...)
        # build_android_app is a built-in fastlane action.

        firebase_app_distribution(
            app: "1:123456789:android:abcd1234",
            testers: "tester1@company.com, tester2@company.com",
            release_notes: "Lots of amazing new features to test out!",
            android_artifact_type:"AAB",
          android_artifact_path: '../build/app/outputs/bundle/release/app-release.aab',
        )

    end
end

**Comment by nidovic** [comment]
platform :android do
    desc "My awesome app"
    lane :distribute do
        build_android_app(task: "bundle", ...)
        # build_android_app is a built-in fastlane action.

        firebase_app_distribution(
            app: "1:123456789:android:abcd1234",
            testers: "tester1@company.com, tester2@company.com",
            release_notes: "Lots of amazing new features to test out!",
            android_artifact_type:"AAB",
            android_artifact_path: '../build/app/outputs/bundle/release/app-release.aab',
        )

    end
end
