### ISSUE TITLE
How to handle Android multiple APKs (split per arch)

### ISSUE THREAD

**Issue by Aure77** [fastlane-community/fastlane-plugin-firebase_app_distribution#27]
Android allow to split my app per CPU arch into multiple APKs to submit smaller app to store.
There is a way to push to firebase all generated APKs ?
If don't specify `apk_path` option, this plugin use the first apk found.
I don't know how to specify multiple path on `apk_path`. Is it possible ?

**Comment by lll8033** [comment]
Hi Aure77, currently split APK is not support by app distribution. Each apk has to be uploaded separately and treated individually.

**Comment by tenhishadow** [comment]
@Aure77 you could specify "apks/flavor/app-arm64-v8a-flavor.apk" with apk_path cause it common for most devices.
Or you could modify your gradle scripts for create build variants like:

one apk for Firebase
split by arch for GooglePlay

**Comment by Aure77** [comment]
There is a way to use wildcards in apk_path ? (For example, apks/*/app-arm64-v8a-*.apk)

**Comment by tenhishadow** [comment]
you could use sh action to set up ENV variable for finding correct apk and catch error if it's not presented.
It's just on-spot idea

https://docs.fastlane.tools/actions/sh/

smth like 
```
sh("export AAA=$( find ./apks -type f -name -type f -name *arm64*.apk)")
```

or something on Ruby

**Comment by Aure77** [comment]
Thx. I found this trick in pure ruby (after a gradle task) :
```
apkPaths = lane_context[SharedValues::GRADLE_ALL_APK_OUTPUT_PATHS] || []
apkArmv8Path = apkPaths.find { |path| path.include?("arm64-v8a") }
```
