### ISSUE TITLE
Proposal: return direct link for download

### ISSUE THREAD

**Issue by tenhishadow** [fastlane-community/fastlane-plugin-firebase_app_distribution#28]
Is it possible to return direct for downloading uploaded build?
I mean that it would be very easy to have direct link integrated with Jira or smth else to download certain build for certain PR in case of CI/CD

**Comment by karimbutt** [comment]
+1

**Comment by cvaghela** [comment]
It isn't possible right now, but it's a feature that the team would like to work on in the future.

**Comment by tenhishadow** [comment]
@cvaghela ok, thanks
