### ISSUE TITLE
Add support for authentication token

### ISSUE THREAD

**Issue by markus-mohemian** [fastlane-community/fastlane-plugin-firebase_app_distribution#5]
As pointed out here https://firebase.google.com/docs/cli#cli-ci-systems adding support for `token` would be super helpful in order to run jobs on CI systems.

**Comment by tagboola** [comment]
Thanks for the suggestion. We've heard this feedback from a few people and plan on addressing it soon. We'll get back to you when we this is done.

**Comment by rebehe** [comment]
Hi Markus, this functionality got added in version `0.1.3`, via the param `firebase_cli_token`. Run `fastlane update_plugins` to pull down this latest version :)
